const express=require("express");
const Approuter=express.Router();
const LocationController=require("../Appcontrollers/LocationController");
const RestaurentController=require("../Appcontrollers/RestaurentController");
const MenuItemController=require("../Appcontrollers/MenuItemsController");
const MealTypecontroller=require("../Appcontrollers/RestaurentController");
const UserController=require("../Appcontrollers/UserController");
const PaymentController=require("../Appcontrollers/PaymentController");
Approuter.get("/Get-Location-List",LocationController.GetLocationList);
Approuter.get("/Get-restaurent-List-By-location-id/:locId",RestaurentController.GetRestaurentListByLocationId);
Approuter.get("/Get-restaurent-Details-by-id/:restId",RestaurentController.GetRestaurentDetailsById);
Approuter.get("/Get-menu-items-by-restaurent-id/:restId",MenuItemController.GetMenuItemsByRestaurentId);
Approuter.get("/Get-meal-type-List",MealTypecontroller.GetMealTypeList);
Approuter.post("/create-user-account",UserController.createUseraccount);
Approuter.post("/user-login",UserController.userLogin);
Approuter.post("/filter",RestaurentController.Filter);
Approuter.post("/Create-order-id",PaymentController.CreateOrderId);
Approuter.post("/verify-payment",PaymentController.VerifyPayment);
Approuter.get("/practise",RestaurentController.PractiseSort);
module.exports=Approuter;